config/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from firstapp import views
from . import views as config_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index1/', views.index1),
    path('index2/', views.index2),
    path('home/', config_views.home),
    path('', config_views.index, name='index'),

    path('first/', include('firstapp.urls')),
    path('second/', include('secondapp.urls')),
    path('third/', include('thirdapp.urls')),
    path('member/', include('member.urls')),
    path('file/', include('file.urls')),
]   + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

file/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name='file'


urlpatterns=[
    path('upload1/', views.upload1, name='upload1'),
    path('upload2/', views.upload2, name='upload2'),
    path('upload3/', views.upload3, name='upload3'),

]

firstapp/urls.py
from django.urls import path
from . import views

app_name = 'firstapp'

urlpatterns = [
    path('main/', views.main),
    path('insert/', views.insert),
    path('show/', views.show, name='show'),
    path('req/get/', views.req_get),
    path('req/post/', views.req_post, name='req_post'),
    path('req/ajax4/', views.req_ajax4, name='ajax4'),
    path('static/', views.static),
    path('var/', views.var),
    path('tag/', views.tag),
    path('filter/', views.filter),
    path('template/', views.template),
    path('form/model/', views.form_model),

]

firstapp/models.py
from django.db import models


#DDL + DML
class Curriculum(models.Model):
    name = models.CharField(max_length=255)

firstapp/forms.py
from .models import Curriculum
from django import forms


class CurriculumForm(forms.ModelForm):

    class Meta:
        model = Curriculum
        fields = ['name'] # id 속성은 PK 이므로 사용하지 않음

firstapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Curriculum

from django.shortcuts import redirect
from .forms import CurriculumForm

def index1(request):
    return HttpResponse('<u>Hello</u>')

def index2(request):
    return HttpResponse('<u>Hi</u>')

def main(request):
    return HttpResponse('<u>Main</u>')


def insert(request):
    # 1-linux 입력
    Curriculum.objects.create(name='linux')
    # 2-python 입력
    c = Curriculum(name='python')
    c.save()
    # 3-html/css/js 입력
    Curriculum(name='python').save()
    # 4-django 입력
    Curriculum(name='django').save()
    return HttpResponse('데이터 입력 완료')

def show(request):
    curriculum = Curriculum.objects.all()
    # result = ''
    # for c in curriculum:
    # #  result += c.name + '<br>'
    # return HttpResponse(result)
    return render(
        request, 'show.html',
        {'data':curriculum}
    )

def req_get(request):
    a = request.GET.get('a')
    b = request.GET.get('b')
    c = request.GET['c']
    result = '%s %s %s' % (a, b, c)
    return HttpResponse(result)
    
def req_post(request):
    if request.method == 'POST':
        a = request.POST.get('a')
        b = request.POST.get('b')
        c = request.POST['c']
        result = '%s %s %s' % (a, b, c)
        return HttpResponse(result)
    return render(request, 'firstapp/post.html')


def req_ajax4(request):
    return render(request, 'firstapp/ajax4.html')


def static(request):
    return render(request, 'firstapp/static.html')

def var(request):
    data = {
        'str': 'text', 'num': 10,
        'list': [1, 2, 3],
        'dict': {'a': 'aaa', 'b': 'bbb'}
    }
    return render(
        request, 'firstapp/var.html', data)    

def tag(request):
    persons = [
        { 'num': 1, 'name': 'Park', 'score': 100 },
        { 'num': 2, 'name': 'Choi', 'score': 70 },
        { 'num': 3, 'name': 'Kim', 'score': 80 }
    ]
    animals = ['Cat', 'Dog']
    context = {
        'persons': persons,
        'animals': animals
    }
    return render(
        request, 'firstapp/tag.html', context)

import datetime
def filter(request):
    c= Curriculum.objects.all()

    context = {
        'curriculum': c,
        'title': 'Simple Python', 'num': 10,
        'price': 39800.5,
        'animals': ['삵', '칡', '타조', '낙타'],
        'covid': datetime.datetime(2020, 1, 8)
    }
    return render(request, 'firstapp/filter.html', context)


def template(request):
    return render(
        request, 'firstapp/template.html',{})


def form_model(request):
  if request.method == 'POST':
    name = request.POST.get('name')
    c = Curriculum(name=name)
    c.save()

    form = CurriculumForm(request.POST)
    if form.is_valid():
      # commit False 사용 시 Curriculum 모델클래스로 반환
      c = form.save(commit=False)
      c.save()      
      return redirect('/first/form/model/')

  else:
    form = CurriculumForm()

  return render(
    request, 'firstapp/form_model.html',
    { 'form': form }
  )

firstapp/templates/firstapp/ajax4.html
{% csrf_token %}

<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        const csrfmiddlewaretoken = document.querySelector('[name=csrfmiddlewaretoken]')
        const formData = new FormData();
        formData.append('a', 10);
        formData.append('b', 20);
        formData.append('c', 30);
        formData.append('csrfmiddlewaretoken', csrfmiddlewaretoken.value);
    
        const data = axios({
        url: '{%url "firstapp:req_post"%}',
        method: 'post',
        data: formData
    });
    data.then(function (result) {
        console.log(result.data);
    });
</script>

firstapp/templates/firstapp/form_model.html
<link rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<div class="container">
<h5 class="my-3 border-bottom pb-2">과목 등록</h5>
<form method="post" action="/first/form/model/"
class="post-form my-3">
{% csrf_token %}

<div class="form-group">
  <label for="name">과목</label>
  <input type="text" class="form-control" name="name" id="name"
    value="{{ form.name.value | default_if_none:'' }}">
</div>

<input type="submit" value="등록" class='btn btn-primary'>
</form>
</div>

firstapp/templates/firstapp/layout.html
<h1>Base Layout</h1>
<div style='background: cyan;'>
<h1>Header</h1>
    {% block content2 %}
    {% endblock %}
</div>

<div style='background: yellow;'>
    <h1>Content</h1>
    {% block content %}
    {% endblock %}
</div>

<div style='background: gray;'>
    <h1>Footer</h1>
    {% block footer %}
    {% endblock %}
</div>

firstapp/templates/firstapp/post.html
<form action="/first/req/post/" method="post">
    <input type="text" name="a"><br>
    <input type="text" name="b"><br>
    <input type="text" name="c"><br>
    {% csrf_token %}
    <button>Send</button>
</form>

firstapp/templates/firstapp/static.html
{% load static%}

<img src='/static/luffy.jpg' width='100px'>
<img src='{% static "luffy.jpg" %}' width='100px'>
<img src='http://ggoreb.com/images/luffy.jpg' width='100px'>

firstapp/templates/firstapp/tag.html
<ul>
    {% for person in persons %}
    <li id='a{{forloop.counter}}'>
        {{forloop.counter}}
        {{ person.num }}, {{ person.name }}, {{ person.score }}</li>
    {% endfor %}
    
</ul>
    {% if 'Cat' in animals %} 🐈 {% endif %}
    {% if 'Tiger' not in animals %} 🐕 {% endif %}

firstapp/templates/firstapp/template.html
{% extends 'firstapp/layout.html' %}
{% block content %}
<form>
    아 이 디 : <input type="text"><br>
    비밀번호 : <input type="text">
</form>
{% endblock %}
{% block footer %}
<address>부산 해운대구 우동</address>
{% endblock %}
{% block header %}
<h4>
    부산 해운대구 중동 ·좌동 ·우동에 걸쳐 있는 해수욕장.
    백사장 길이 1.8km, 너비 35~50m, 면적 7만 2000㎡이다.
</h4>
{% endblock %}

firstapp/templates/firstapp/var.html
<h3>문자 및 숫자</h3>
<p>{{ str }} / {{ num }}</p><hr>
<h3>리스트</h3>
<p>{{ list.0 }} / {{ list.1 }} / {{ list.2 }}</p><hr>
<h3>딕셔너리</h3>
<p>{{ dict.a }} / {{ dict.b }}</p><hr>