config/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from firstapp import views
from . import views as config_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index1/', views.index1),
    path('index2/', views.index2),
    path('home/', config_views.home),
    path('', config_views.index, name='index'),

    path('first/', include('firstapp.urls')),
    path('second/', include('secondapp.urls')),
    path('third/', include('thirdapp.urls')),
    path('member/', include('member.urls')),
    path('file/', include('file.urls')),
]   + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

file/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name='file'


urlpatterns=[
    path('upload1/', views.upload1, name='upload1'),
    path('upload2/', views.upload2, name='upload2'),
    path('upload3/', views.upload3, name='upload3'),

]

member/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name='member'


urlpatterns=[
    path('login/',
         auth_views.LoginView.as_view(
            template_name='member/login.html'
         ),
          name='login' 
    ),

    path('logout/',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),
    path('signup/', views.signup, name='signup'),

]

member/models.py
from django.db import models

# Create your models here.

member/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    class Meta:
        model = User
        fields = ("username", "email")

member/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import UserForm

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()

        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')

        user = authenticate(username=username, password=raw_password)
        login(request, user)
        return redirect('index')
    else:
        form = UserForm()
    return render(request, 'member/signup.html', {'form': form})

member/templates/member/login.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<div class="container my-3">
    <form method="post" class="post-form" action="{% url 'member:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value | default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                value="{{ form.password.value | default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>

    </form>
    {% if user.is_authenticated %}
    
    <p>
        <a class='nav-link' href="{% url 'member:logout' %}">
            {{ user.username }} 님 반갑습니다. (로그아웃)
        </a> 
    </p>
    
        {% else %}
    <p>현재 상태 : Guest</p>
    {% endif %}
    </div>

</div>

member/templates/member/signup.html
<link rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<div class="container my-3">
<div class="row my-3">
<div class="col-4">
<h4>계정생성</h4>
</div>
<div class="col-8 text-right">
<span>또는 <a href="{% url 'member:login' %}">로그인 하세요.</a></span>
</div>
</div>
<form method="post" class="post-form">
{% csrf_token %}
{% include "form_errors.html" %}
<div class="form-group">
    <label for="username">사용자 이름</label>
    <input type="text" class="form-control" name="username" id="username"
    value="{{ form.username.value | default_if_none:'' }}">
    </div>
    <div class="form-group">
    <label for="password1">비밀번호</label>
    <input type="password" class="form-control" name="password1"
    id="password1" value="{{ form.password1.value | default_if_none:'' }}">
    </div>
    <div class="form-group">
    <label for="password2">비밀번호 확인</label>
    <input type="password" class="form-control" name="password2"
    id="password2" value="{{ form.password2.value | default_if_none:'' }}">
    </div>
    <div class="form-group">
    <label for="email">이메일</label>
    <input type="text" class="form-control" name="email"
    id="email" value="{{ form.email.value | default_if_none:'' }}">
    </div>
    <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
    </div>